"""Build a TAAC-platform-friendly upload bundle for one experiment.

Per the platform's Training Code page (see screenshot), uploads are a flat
list of files (no subdirectories). The platform sets ``TRAIN_DATA_PATH``,
``TRAIN_CKPT_PATH`` (and optionally ``TRAIN_LOG_PATH``, ``TRAIN_TF_EVENTS_PATH``)
as env vars, then invokes ``bash run.sh``.

This script produces:

    experiments/{exp_id}/upload/
    ├── dataset.py        (patched: v2 split + OOF holdout)
    ├── model.py
    ├── ns_groups.json
    ├── run.sh            (platform-tailored — generated, NOT competition/run.sh)
    ├── train.py          (patched: --use_label_time_split etc.)
    ├── trainer.py        (graceful tqdm fallback)
    ├── utils.py
    ├── make_schema.py    (added — auto-generates schema.json)
    └── README.md         (technical report stub + run instructions)

Plus a backup archive ``experiments/{exp_id}/upload.tar.gz`` for re-download
in case the browser drops a file during upload.

The user uploads each file individually through the platform UI ("Upload
from Local"). Total size cap on the platform side is 100 MB; our bundle is
typically < 200 KB so well under cap.

Usage:
    python skills/_helpers/build_cloud_package.py \
        --exp-id E000_unified_baseline_demo
"""

import argparse
import os
import shutil
import sys
import tarfile
from pathlib import Path

# Files copied verbatim from competition/.
COMPETITION_FILES = [
    "dataset.py",
    "model.py",
    "ns_groups.json",
    "train.py",
    "trainer.py",
    "utils.py",
    "make_schema.py",
]

# Submission entry point — colocated with training code in the platform's flat
# namespace. The platform may require this file's presence for storage
# provisioning even on training-only jobs (defensive include).
SUBMISSION_FILES = [
    ("submission/infer.py", "infer.py"),
    ("submission/local_validate.py", "local_validate.py"),
]

REQUIREMENTS_PIN = """\
torch>=2.0,<3.0
pyarrow>=14.0,<24.0
numpy>=1.24,<3.0
scikit-learn>=1.3
tqdm>=4.65
tensorboard>=2.14
"""


def _platform_run_sh(exp_id: str, card_summary: str, mode: str = "patched",
                     extra_args: str = "") -> str:
    """Generate a flat-namespace run.sh tuned for the platform.

    Two modes:
    - ``patched``: our v2 inline-filter split + OOF holdout (default).
    - ``organizer``: organizer's run.sh as-shipped — row-group split, no OOF.
    """
    common_header = f"""#!/bin/bash
# Platform run.sh for {exp_id} — mode={mode}
# {card_summary}
# Generated by skills/_helpers/build_cloud_package.py — do not hand-edit on platform.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
export PYTHONPATH="${{SCRIPT_DIR}}:${{PYTHONPATH:-}}"

# ---------------------------------------------------------------------------
# Platform must set TRAIN_DATA_PATH and TRAIN_CKPT_PATH. Other paths derive.
# ---------------------------------------------------------------------------
: "${{TRAIN_DATA_PATH:?TRAIN_DATA_PATH not set by platform}}"
: "${{TRAIN_CKPT_PATH:?TRAIN_CKPT_PATH not set by platform}}"
: "${{TRAIN_LOG_PATH:=${{TRAIN_CKPT_PATH}}/logs}}"
: "${{TRAIN_TF_EVENTS_PATH:=${{TRAIN_CKPT_PATH}}/tf_events}}"
: "${{TRAIN_WORK_PATH:=${{TRAIN_CKPT_PATH}}/work}}"
mkdir -p "${{TRAIN_CKPT_PATH}}" "${{TRAIN_LOG_PATH}}" "${{TRAIN_TF_EVENTS_PATH}}" "${{TRAIN_WORK_PATH}}"
export TRAIN_LOG_PATH TRAIN_TF_EVENTS_PATH

echo "[run.sh] DATA=${{TRAIN_DATA_PATH}}"
echo "[run.sh] CKPT=${{TRAIN_CKPT_PATH}}"
echo "[run.sh] mode={mode}"
"""

    extra_args_block = ""
    if extra_args.strip():
        tokens = extra_args.strip().split()
        lines = []
        i = 0
        while i < len(tokens):
            t = tokens[i]
            if i + 1 < len(tokens) and not tokens[i + 1].startswith("--"):
                lines.append(f"    {t} {tokens[i + 1]} \\")
                i += 2
            else:
                lines.append(f"    {t} \\")
                i += 1
        extra_args_block = "\n".join(lines) + "\n"

    if mode == "organizer":
        body_lines = [
            "",
            "# ---------------------------------------------------------------------------",
            "# Train (organizer baseline as-shipped — row-group split, no OOF).",
            "# Smoke-test defaults: --train_ratio 0.05 + halved seq_max_lens.",
            "# ---------------------------------------------------------------------------",
            'python3 -u "${SCRIPT_DIR}/train.py" \\',
            "    --num_epochs 1 \\",
            "    --patience 5 \\",
            "    --seed 42 \\",
            "    --ns_tokenizer_type rankmixer \\",
            "    --user_ns_tokens 5 \\",
            "    --item_ns_tokens 2 \\",
            "    --num_queries 2 \\",
            '    --ns_groups_json "" \\',
            "    --emb_skip_threshold 1000000 \\",
            "    --num_workers 2 \\",
            "    --buffer_batches 4 \\",
            "    --train_ratio 0.05 \\",
            '    --seq_max_lens "seq_a:64,seq_b:64,seq_c:128,seq_d:128" \\',
        ]
        body = "\n".join(body_lines) + "\n"
        if extra_args_block:
            body += extra_args_block
        body += '    "$@"\n'
        body += '\necho "[run.sh] training complete (organizer); metrics at ${TRAIN_CKPT_PATH}/metrics.json"\n'
        return common_header + body

    # Default: patched (our v2 inline filter).
    body_lines = [
        "",
        "# ---------------------------------------------------------------------------",
        "# Step 0: resolve schema.json (DATA → WORK → generate).",
        "# ---------------------------------------------------------------------------",
        'DATA_SCHEMA="${TRAIN_DATA_PATH}/schema.json"',
        'WORK_SCHEMA="${TRAIN_WORK_PATH}/schema.json"',
        'if [[ -f "${DATA_SCHEMA}" ]]; then',
        '    SCHEMA_JSON="${DATA_SCHEMA}"',
        '    echo "[run.sh] using organizer-provided schema.json: ${SCHEMA_JSON}"',
        'elif [[ -f "${WORK_SCHEMA}" ]]; then',
        '    SCHEMA_JSON="${WORK_SCHEMA}"',
        '    echo "[run.sh] using cached schema.json: ${SCHEMA_JSON}"',
        "else",
        '    SCHEMA_JSON="${WORK_SCHEMA}"',
        '    echo "[run.sh] generating schema.json -> ${SCHEMA_JSON}"',
        '    python3 "${SCRIPT_DIR}/make_schema.py" \\',
        '        "${TRAIN_DATA_PATH}" "${SCHEMA_JSON}" \\',
        '        --max-row-groups-per-file "${SCHEMA_MAX_RG_PER_FILE:-1}" \\',
        '        --vocab-safety-mult "${SCHEMA_VOCAB_MULT:-10}"',
        "fi",
        'echo "[run.sh] schema ready at ${SCHEMA_JSON}"',
        "",
        "# ---------------------------------------------------------------------------",
        "# Step 1: train (label_time-aware split + 10% user OOF holdout, inline filter).",
        "# ---------------------------------------------------------------------------",
        'python3 -u "${SCRIPT_DIR}/train.py" \\',
        "    --num_epochs 1 \\",
        "    --patience 5 \\",
        "    --seed 42 \\",
        '    --schema_path "${SCHEMA_JSON}" \\',
        "    --use_label_time_split \\",
        "    --oof_user_ratio 0.1 \\",
        "    --split_seed 42 \\",
        '    --work_dir "${TRAIN_WORK_PATH}" \\',
        "    --ns_tokenizer_type rankmixer \\",
        "    --user_ns_tokens 5 \\",
        "    --item_ns_tokens 2 \\",
        "    --num_queries 2 \\",
        '    --ns_groups_json "" \\',
        "    --emb_skip_threshold 1000000 \\",
        "    --num_workers 2 \\",
        "    --buffer_batches 4 \\",
        '    --seq_max_lens "seq_a:64,seq_b:64,seq_c:128,seq_d:128" \\',
    ]
    body = "\n".join(body_lines) + "\n"
    if extra_args_block:
        body += extra_args_block
    body += '    "$@"\n'
    body += '\necho "[run.sh] training complete (patched); metrics at ${TRAIN_CKPT_PATH}/metrics.json"\n'
    return common_header + body


def _platform_readme(exp_id: str, claim: str, hypothesis_id: str,
                     compute_tier: str, expected_wall: str) -> str:
    """Generate README.md (technical report stub + run instructions)."""
    return f"""# {exp_id} — Technical Report

> Required during Final Round per the platform notice. Currently a working
> stub describing the baseline run; flesh out for Final Round submission.

## 1. Hypothesis & Claim
- Hypothesis: **{hypothesis_id}**
- Claim: {claim}
- Compute tier (suggested): **{compute_tier}**
- Expected wall (suggested): {expected_wall}

## 2. What this code does
Trains the organizer's PCVRHyFormer (multi-domain sequence encoders →
per-domain query decoders → joint token fusion via RankMixer) with two
patches:

- **`label_time`-aware split** (instead of organizer's row-group order)
  — prevents exposure → feedback leakage and works on single-row-group
  parquet files.
- **10% user_id OOF holdout** (seed=42) — held out from BOTH train and
  valid so the reported `best_oof_AUC` is a true generalization estimate.

Schema is auto-generated by `make_schema.py` if missing — vocab sizes,
list dims, and per-domain `ts_fid` are inferred from the parquet metadata.

## 3. Files
| File | Purpose |
|---|---|
| `run.sh` | Entry point — platform invokes `bash run.sh`. |
| `make_schema.py` | Auto-generates `schema.json` from training parquet metadata. |
| `train.py` | Trainer driver (CLI flags + dual optimizer wiring). |
| `trainer.py` | Pointwise BCE/Focal training loop, AUC + logloss validation. |
| `model.py` | `PCVRHyFormer` (1714 lines, organizer-supplied). |
| `dataset.py` | `PCVRParquetDataset` + patched `get_pcvr_data_v2` for label_time split. |
| `utils.py` | Logger, EarlyStopping, focal loss helper. |
| `ns_groups.json` | NS-token feature grouping reference (currently unused — `--ns_groups_json ""` in run.sh). |

## 4. Platform contract
The platform must set:
- `TRAIN_DATA_PATH` — directory containing training `*.parquet`.
- `TRAIN_CKPT_PATH` — writable directory for checkpoints + `metrics.json`.
- (optional) `TRAIN_LOG_PATH`, `TRAIN_TF_EVENTS_PATH` — derive from CKPT if unset.

Then invoke `bash run.sh`.

## 5. Outputs
- `${{TRAIN_CKPT_PATH}}/metrics.json` — primary reporting source. Includes
  `best_val_AUC`, `best_oof_AUC`, `split_meta`, `seed`, `git_sha`,
  `config_sha256`, `host`.
- `${{TRAIN_CKPT_PATH}}/global_step*.best_model/` — model.pt + schema.json
  + train_config.json (used by inference).
- `${{TRAIN_LOG_PATH}}/train.log` — full training log.

## 6. Sanity dry-run
For a 30-second pipeline check before the full run:
```
bash run.sh --num_epochs 1 --batch_size 32
```

## 7. Method extensions over organizer baseline (for Final Round)
- (Fill with cumulative changes as new hypotheses land.)
- Currently: zero architectural mutation. Future iterations swap one
  component class per hypothesis (CLAUDE.md §17.2).

## 8. Reproducibility
- All seeds fixed (default 42); cuDNN deterministic mode set in `utils.set_seed`.
- `--seed` overrides for multi-seed campaigns.
- `metrics.json` records git SHA + config SHA256 for traceability.
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exp-id", required=True,
                        help="experiment dir name under experiments/")
    parser.add_argument("--mode", choices=["patched", "organizer"], default="patched",
                        help="run.sh template: 'patched' (our v2 inline filter, default) "
                             "or 'organizer' (competition baseline as-shipped, no OOF)")
    parser.add_argument("--extra-args", default="",
                        help="extra args appended to train.py invocation in run.sh "
                             "(e.g. '--enable_inter_domain_bridges --bridge_rank 4')")
    parser.add_argument("--root", default=None,
                        help="project root (default: detect)")
    args = parser.parse_args()

    root = Path(args.root) if args.root else Path(__file__).resolve().parents[2]
    exp_dir = root / "experiments" / args.exp_id
    if not exp_dir.is_dir():
        print(f"ERROR: experiment not found: {exp_dir}", file=sys.stderr)
        return 1

    upload = exp_dir / "upload"
    if upload.exists():
        shutil.rmtree(upload)
    upload.mkdir(parents=True)

    # 1. Copy the competition files verbatim.
    competition = root / "competition"
    for fname in COMPETITION_FILES:
        src = competition / fname
        if not src.exists():
            print(f"ERROR: competition file missing: {src}", file=sys.stderr)
            return 1
        shutil.copy2(src, upload / fname)
        print(f"  + {fname}  ({src.stat().st_size / 1024:.1f}K)")

    # 1b. Copy submission entry points (infer.py + local_validate.py).
    #     Some platforms require infer.py present for user-storage provisioning
    #     even on training jobs.
    for src_rel, dst_name in SUBMISSION_FILES:
        src = root / src_rel
        if not src.exists():
            print(f"WARNING: submission file missing, skipping: {src}", file=sys.stderr)
            continue
        shutil.copy2(src, upload / dst_name)
        print(f"  + {dst_name}  ({src.stat().st_size / 1024:.1f}K, from submission/)")

    # 2. Generate the platform-tailored run.sh (replaces competition/run.sh,
    #    which has local-dev assumptions).
    card_summary = "see README.md §1 (Hypothesis & Claim)."
    run_sh_content = _platform_run_sh(args.exp_id, card_summary, mode=args.mode,
                                      extra_args=args.extra_args)
    (upload / "run.sh").write_text(run_sh_content)
    os.chmod(upload / "run.sh", 0o755)
    print(f"  + run.sh  ({len(run_sh_content) / 1024:.1f}K, generated)")

    # 3. Generate README.md from card.yaml metadata.
    card_yaml = exp_dir / "card.yaml"
    claim = "(card.yaml missing)"
    hypothesis_id = ""
    compute_tier = ""
    expected_wall = ""
    if card_yaml.exists():
        text = card_yaml.read_text()
        for line in text.splitlines():
            if line.startswith("hypothesis_id:"):
                hypothesis_id = line.split(":", 1)[1].strip()
            elif line.startswith("compute_tier:"):
                compute_tier = line.split(":", 1)[1].strip()
            elif line.startswith("treatment:"):
                claim = line.split(":", 1)[1].strip().strip('"')
            elif line.startswith("expected_wall_min:"):
                expected_wall = f"~{line.split(':', 1)[1].strip()} min"
    readme = _platform_readme(args.exp_id, claim, hypothesis_id,
                              compute_tier, expected_wall)
    (upload / "README.md").write_text(readme)
    print(f"  + README.md  ({len(readme) / 1024:.1f}K, generated)")

    # 4. Pinned requirements (informational — platform may pre-install).
    (upload / "requirements.txt").write_text(REQUIREMENTS_PIN)
    print(f"  + requirements.txt  ({len(REQUIREMENTS_PIN) / 1024:.1f}K)")

    # 5. Backup tarball — if the user's browser drops a file mid-upload,
    #    they can re-extract from this archive.
    backup = exp_dir / "upload.tar.gz"
    if backup.exists():
        backup.unlink()
    with tarfile.open(backup, "w:gz") as tar:
        for entry in sorted(upload.iterdir()):
            tar.add(entry, arcname=entry.name)

    total_kb = sum(p.stat().st_size for p in upload.iterdir()) / 1024
    print(f"\nupload dir: {upload}")
    print(f"backup tar: {backup}  ({backup.stat().st_size / 1024:.1f}K)")
    print(f"total: {total_kb:.1f}K   (platform cap: 100.0M)")
    print(f"\nfile manifest (matches platform 'Training Code' table):")
    for entry in sorted(upload.iterdir()):
        kb = entry.stat().st_size / 1024
        print(f"  {entry.name:<22}  {kb:>8.1f}K")
    return 0


if __name__ == "__main__":
    sys.exit(main())
